language: ruby
rvm:
  - 2.3.1
  - 2.2.2
env:
  - DB=postgresql
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
